name: E-Stock

services:

  db:
    image: mysql:latest
    container_name: db
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8080:80
    networks:
      - app
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_PORT: 3306

volumes:
  db-data:

networks:
  app:
    driver: bridge
